apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: h97b7iyrk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h97b7iyrk-go 
  name: h97b7iyrk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: h97b7iyrk-go 
